debug: "${DEBUG:false}"

server:
  port: "${APP_PORT:3000}"
  address: "${APP_ADDRESS:0.0.0.0}"
  shutdown: graceful
  servlet:
    context-path: ""
    session:
      cookie:
        http-only: true
        secure: true
  error:
    include-binding-errors: never
    include-message: never
    include-path: always
    include-stacktrace: never
    include-exception: false

spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  application:
    name: "@project.artifactId@"
  output:
    ansi:
      enabled: never
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
  mvc:
    problemdetails:
      enabled: true
  messages:
    basename: "classpath:i18n/messages"
    encoding: utf-8
    always-use-message-format: true
    use-code-as-default-message: false
    cache-duration: "30s"
    fallback-to-system-locale: true
  web:
    locale: "${APP_LOCALE}"
  thymeleaf:
    enable-spring-el-compiler: true
    cache: false
    encoding: UTF-8

management:
  server:
    port: "${MANAGMENT_PORT:9090}"
  endpoints:
    enabled-by-default: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: "${RESILIENCE4J_MAX_RETRY}"
        wait-duration: "${RESILIENCE4J_WAIT_DURATION}"
        fail-after-max-attempts: true
        enable-exponential-backoff: true
        exponential-backoff-multiplier: "${RESILIENCE4J_BACKOFF_MULTIPLIER}"
        exponential-max-wait-duration: "${RESILIENCE4J_MAX_WAIT_DURATION}"
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - java.net.SocketTimeoutException

app:
  internalization:
    default-locale: en
  template:
    config:
      html:
        prefix: "classpath:templates/html/"
        suffix: ".html"
        cacheable: false
      css:
        prefix: "classpath:static/css/"
        suffix: ".css"
      js:
        prefix: "classpath:static/js/"
        suffix: ".js"
