debug: "${DEBUG:false}"

server:
  port: "${APP_PORT:8080}"
  address: "${APP_ADDRESS:0.0.0.0}"
  shutdown: graceful
  servlet:
    context-path: "${APP_CONTEXT_PATH:}"
    session:
      cookie:
        http-only: true
        secure: true
  error:
    include-binding-errors: never
    include-message: never
    include-path: always
    include-stacktrace: never
    include-exception: false

spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  application:
    name: "@project.artifactId@"
  output:
    ansi:
      enabled: never
  main:
    banner-mode: off
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:h2-init.sql'"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      auto-commit: true
      max-lifetime: 3600000
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
  mvc:
    problemdetails:
      enabled: true
  messages:
    basename: "classpath:i18n/messages"
    encoding: utf-8
    always-use-message-format: true
    use-code-as-default-message: false
    cache-duration: "30s"
    fallback-to-system-locale: true
  web:
    locale: "${APP_LOCALE:en}"
  thymeleaf:
    enable-spring-el-compiler: true
    cache: false
    encoding: UTF-8
  h2:
    console:
      enabled: true

management:
  server:
    port: "${APP_MANAGMENT_PORT:9090}"
  endpoints:
    enabled-by-default: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: "8"
        wait-duration: "2s"
        fail-after-max-attempts: true
        enable-exponential-backoff: true
        exponential-backoff-multiplier: "1.4"
        exponential-max-wait-duration: "3m"
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - java.net.SocketTimeoutException
      book-repository:
        base-config: "default"
        ignore-exceptions:
          - com.github.overz.errors.BadRequestException

app:
  internalization:
    default-locale: "en"
  template:
    config:
      html:
        prefix: "classpath:templates/html/"
        suffix: ".html"
        cacheable: false
      css:
        prefix: "classpath:templates/css/"
        suffix: ".css"
      js:
        prefix: "classpath:templates/js/"
        suffix: ".js"
