CREATE TABLE Book
(
	cdBook        TEXT NOT NULL,
	nmBook        TEXT NOT NULL,
	nmAuthor      TEXT NOT NULL,
	dsDescription TEXT NOT NULL,
	dtCreatedAt   DATE NOT NULL,
	dtPublishedAt DATE
);

INSERT INTO Book (cdBook, nmBook, nmAuthor, dsDescription, dtCreatedAt)
VALUES (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE),
			 (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE),
			 (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE),
			 (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE),
			 (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE),
			 (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE),
			 (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE),
			 (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE),
			 (RANDOM_UUID(), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), LEFT(RANDOM_UUID(), 15), CURRENT_DATE)
;